### PR TITLE
Bump and migrate to nu-plugin and nu-protocol 0.87

### LINKED ISSUE #1: Plugin failed to decode
When trying to 'register' the plugin, I get:

> Plugin failed to decode: invalid type: string "provider", expected a sequence

Is this my fault, or is this in the plugin source? Cheers

### PR DESCRIPTION
**Pull request by fmotalleb**
closes #1

### CODE REVIEW

**Comment by fmotalleb** [comment]
well the example is so huge that migrating it will be a disaster and also in the terminal it looks like this
```bash
-> from hcl --help
Parse text as .hcl and create a record

Usage:
  > from hcl 

Flags:
  -h, --help - Display the help message for this command

Input/output types:
  ╭───┬────────┬────────╮
  │ # │ input  │ output │
  ├───┼────────┼────────┤
  │ 0 │ string │ record │
  ╰───┴────────┴────────╯

Examples:
  Convert .hcl data into record
  > 'provider "aws" {
  region = "us-east-1"
}
resource "aws_instance" "web" {
  ami           = "ami-a1b2c3d4"
  instance_type = "t2.micro"
}' | from hcl
  ╭──────────┬──────────────────╮
  │ provider │ {record 1 field} │
  │ resource │ {record 1 field} │
  ╰──────────┴──────────────────╯
  ```
  instead of 
  ```bash
  ╭──────────┬───────────────────────────────────────────────────────────────╮
│          │ ╭─────┬────────────────────────╮                              │
│ provider │ │     │ ╭────────┬───────────╮ │                              │
│          │ │ aws │ │ region │ us-east-1 │ │                              │
│          │ │     │ ╰────────┴───────────╯ │                              │
│          │ ╰─────┴────────────────────────╯                              │
│          │ ╭──────────────┬────────────────────────────────────────────╮ │
│ resource │ │              │ ╭─────┬──────────────────────────────────╮ │ │
│          │ │ aws_instance │ │     │ ╭───────────────┬──────────────╮ │ │ │
│          │ │              │ │ web │ │ ami           │ ami-a1b2c3d4 │ │ │ │
│          │ │              │ │     │ │ instance_type │ t2.micro     │ │ │ │
│          │ │              │ │     │ ╰───────────────┴──────────────╯ │ │ │
│          │ │              │ ╰─────┴──────────────────────────────────╯ │ │
│          │ ╰──────────────┴────────────────────────────────────────────╯ │
╰──────────┴───────────────────────────────────────────────────────────────╯
  ```

**Comment by fmotalleb** [comment]
+ If you add the `from tf` signature `open main.tf` will automatically parse it, currently it only supports `hcl`

**Comment by Yethal** [comment]
Oh wow, thank you so much for this!

**Comment by vipau** [comment]
Thank you!

**Pull request merged**
